"""empty message

Revision ID: 9d4c28b51e52
Revises: 70f5b3f8df4d
Create Date: 2021-02-22 19:11:53.100052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4c28b51e52'
down_revision = '70f5b3f8df4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', sa.String(length=250), nullable=False))
    op.drop_constraint('order_ibfk_1', 'order', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('order_ibfk_1', 'order', 'user', ['user_id'], ['id'])
    op.drop_column('order', 'status')
    # ### end Alembic commands ###
