"""empty message

Revision ID: fb1a079e19c8
Revises: 22aab8a2032d
Create Date: 2021-02-17 13:38:54.082521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1a079e19c8'
down_revision = '22aab8a2032d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('user_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_type')
    op.drop_constraint(None, 'order', type_='foreignkey')
    # ### end Alembic commands ###
